#! /usr/bin/env python3

'''Run multiple SSH commands at once from a shell-like REPL'''

import argparse
import atexit
import os
import random
import re
import readline
import sys
from queue import Queue
from shlex import split, quote
from subprocess import run, CompletedProcess, DEVNULL, PIPE, STDOUT
from threading import Thread

# TODO: Ctrl+C should cancel SSH session(s) if running, instead of whole REPL
# TODO: `-n` option to limit concurrent session count
# TODO: list last-world-only completions when there are multiple possibilities

RE_HOST_SPLIT = re.compile(r'[ \t\n,;]+')
RE_META_CMD = re.compile(r'^\s*%\s*(.*)')
RE_IGNORE_PREFIX = re.compile(r'^\s*(?:\$\s+)?', re.M)
RE_EXIT = re.compile(r'^\s*exit\s*(?:#.*)?$')
RE_MOD_HOSTS = re.compile(r'^(\ *([+-])\ *)(.*)')
RE_COMPLETION = re.compile(
    r'^(.*?)(?:^|(?<=[\t\ \n\(\)\[\]\{\}\:\;\&]))([^\ ]*$)'
)


def run_ssh(host: str, cmd: str, q: Queue[tuple[int, str, CompletedProcess]]):
    '''Run bash script putting returncode and output in queue'''
    id = random.randrange(2 ** 128)
    t = Thread(target=_run_ssh, args=(id, host, cmd, q), daemon=True)
    t.start()
    return id


def _run_ssh(
    id: int, host: str, cmd: str, q: Queue[tuple[int, str, CompletedProcess]]
):
    '''helper'''
    q.put((id, host, run(
        ['ssh', host, '--', cmd],
        stdout=PIPE, stderr=STDOUT, stdin=DEVNULL,
        text=True, errors='replace', bufsize=1
    )))


def get_executables(prefix: str = '') -> list[str]:
    '''List executables in path'''
    results = set()
    for dir in os.get_exec_path():
        try:
            files = os.listdir(dir)
        except OSError:
            files = []
        for file in files:
            if not prefix or file.startswith(prefix):
                try:
                    if os.stat(os.path.join(dir, file)).st_mode & 0o111:
                        results.add(file)
                except OSError:
                    pass
    results = sorted(results)
    return [results[0] + ' '] if len(results) == 1 else results


def get_paths(prefix: str = '') -> list[str]:
    '''List paths starting with prefix'''
    dir, isdir, prefix = prefix.rpartition('/')
    dir += isdir
    try:
        return sorted(
            os.path.join(dir, file)
            for file in os.listdir(dir) if file.startswith(prefix)
        )
    except OSError:
        return []


def get_hosts(prefix: str = '') -> list[str]:
    '''List hosts in the ~/.ssh/config'''
    prefix = prefix[1:]
    hosts = {'localhost'} if 'localhost'.startswith(prefix) else set()
    try:
        with open(os.path.expanduser('~/.ssh/config')) as file:
            for line in file:
                if (line.split(None, 1) or '.')[0].lower() == 'host':
                    for host in line.partition('#')[0].split()[1:]:
                        if host.startswith(prefix) and '*' not in host:
                            hosts.add(host)
    except OSError:
        pass
    return sorted(hosts)


_COMPLETION__LIST = []
def completion(text: str, state: int):
    '''Run readline completion

    `readline` calls this function with state 0, 1, 2, ... until it returns None

    The first time it is called with a given text, it computes the list of
    possible completions and stores it to _COMPLETION_LIST, then it return the
    item with index state from that list, or None if there are no more items.
    '''
    if state:
        if state < len(_COMPLETION__LIST):
            return _COMPLETION__LIST[state]
        return None
    _COMPLETION__LIST.clear()
    prefix = ''
    completions = []
    if r := RE_MOD_HOSTS.match(text):
        prefix = r[1]
        completions = get_hosts(r[3])
    elif r := RE_COMPLETION.match(text):
        prefix = r[1]
        completions = get_executables(r[2]) + get_paths(r[2])
    if len(completions) > 1:
        _COMPLETION__LIST.extend(prefix + c for c in completions)
    elif completions:
        _COMPLETION__LIST.append(prefix + completions[0])
    else:
        return None
    return _COMPLETION__LIST[0]


def get_readline_backend() -> str:
    '''Get readline backend `'gnu_readline'` (GNU), `'libedit'` BSD, or `'?'`'''
    if 'libedit' in (doc := getattr(readline, '__doc__', '').lower()):
        return 'libedit'
    elif 'readline' in doc.lower():
        return 'gnu_readline'
    return 'libedit' if 'libedit' in getattr(readline, '__file__', '') else '?'


def setup_readline():
    '''Set up the readline module (call this only once!)'''
    if os.path.isfile(path := os.path.expanduser('~/.inputrc')):
        readline.read_init_file(path)
    if os.path.isfile(path := os.path.expanduser('~/.mush_history')):
        readline.read_history_file(path)
    atexit.register(readline.write_history_file, path)
    readline.set_completer(completion)
    readline.set_completer_delims(' \t\n')
    if get_readline_backend() == 'libedit':
        readline.parse_and_bind('bind ^I rl_complete')
    else:
        readline.parse_and_bind('tab: complete')
    


def format(host: str, code: int, text: str) -> str:
    '''Format response text for output'''
    if code:
        msg = f'\033[31;1m⪡ {host}\033[22m ({code})\033[39m'
        return msg + f'\n\033[2m{text}\033[22m'
    msg = f'\033[34;1m⪡ {host}\033[22m ({code})\033[39m'
    return msg + f'\n\033[2m{text}\033[22m'


def main():
    '''run script'''
    # parse arguments
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        'host', nargs='+',
        help='host(s) to connect to'
    )
    p.add_argument(
        '-m', '--merge', action='store_true',
        help='merge together identical output'
    )
    a = p.parse_args()
    # store positions of hosts for use later
    hosts_ref: dict[str, int] = {}
    for host in a.host:
        if host not in hosts_ref:
            hosts_ref[host] = len(hosts_ref)
    # setup
    setup_readline()
    # repl loop
    q: Queue[tuple[int, str, CompletedProcess]] = Queue()
    while True:
        cmd = input('⫸ ')
        # meta commands
        if r := RE_META_CMD.match(cmd):
            # add or remove host(s)
            if r[1][:1] in ('+', '-'):
                adding = r[1][0] == '+'
                for host in split(cmd[1:]):
                    if host.startswith(('+', '-')):
                        adding = host[0] == '+'
                        if not (host := host[1:]):
                            continue
                    if adding:
                        if host not in hosts_ref:
                            hosts_ref[host] = max(hosts_ref.values()) + 1
                    elif host in hosts_ref:
                        del hosts_ref[host]
                continue
            else:
                sys.stderr.write(f'unrecognized meta command: {quote(r[1])}\n')
                continue
        # system exit
        if RE_EXIT.match(cmd):
            sys.exit()
        # regular command
        cmd = RE_IGNORE_PREFIX.sub('', cmd)
        # send command to all hosts
        hosts = {}
        for host in hosts_ref:
            hosts[run_ssh(host, cmd, q)] = host
        # retrieve results from all hosts
        got_responses = {id: False for id in hosts}
        response2hosts: dict[tuple[int, str], list[str]] = {}
        host2response: dict[str, tuple[int, str]] = {}
        for i in range(len(hosts_ref), 0, -1):
            # show remaining hosts
            msg = f'waiting for {i} / {len(a.host)}: ' + ', '.join(
                hosts[id] for id, got_it in got_responses.items() if not got_it
            )
            if not a.merge:
                sys.stderr.write('\n')
            sys.stderr.write(f'\033[33m{msg}\033[39m')
            sys.stderr.flush()
            # receive response from next host
            id, host, proc = q.get()
            got_responses[id] = True
            # clear remaining hosts message
            sys.stderr.write('\010' * len(msg) + '\033[J')
            sys.stderr.flush()
            # store response
            if a.merge:
                host2response[host] = response = proc.returncode, proc.stdout
                response2hosts.setdefault(response, []).append(host)
                continue
            # show response (error)
            sys.stdout.write(format(host, proc.returncode, proc.stdout))
            sys.stdout.flush()
        sys.stdout.write('\n')
        # show merged responses
        if a.merge:
            for host in hosts_ref:
                code, text = host2response[host]
                if response_hosts := response2hosts.get((code, text)):
                    hosts_str = ', '.join(sorted(
                        response_hosts, key=(lambda h: hosts_ref[h])
                    ))
                    sys.stdout.write(format(hosts_str, code, text) + '\n')
                    del response2hosts[(code, text)]


if __name__ == '__main__':
    try:
        main()
    except (EOFError, KeyboardInterrupt):
        sys.stderr.write('\n')
